### ISSUE TITLE
[Enhancement]: Add custom saved prompts

### ISSUE THREAD

**Issue by guilhermelimak** [maxijonson/gpt-turbo#16]
### Scope

Web (gpt-turbo-web)

### Type

New feature

### Description

I'm not sure this is in the scope of this application but would be very nice to be able to save custom prompts and start conversations with them. I have some prompts that I use a lot and ended up storing them in a markdown file and copy-pasting them when needed.

The main points would be:

- Users should be able to view a list with custom prompts (maybe in a modal?)
- Users should be able to add/delete/edit custom prompts that they created
- Users should be able to select a custom prompt from a select input when starting a new conversation
- Users should not be able to see other users prompts or have any kind of cloud like functionality
- User prompts should be stored in the user browser (maybe localstorage or something like that) and would be lost when clearing cache (just to avoid all the work of syncing it)

It is a somewhat complex feature so I would definitely understand if you think it shouldn't be added.

### Benefit

Users would have easy access to prompts they use a lot when creating a new conversation, making it easy to do repetitive tasks in different conversations (like generating code or translating text)

### Participation

Yes

**Comment by maxijonson** [comment]
Hey! Thanks for opening an issue. 

Yes, that would be a good idea, especially for context (system) prompts. I would suggest some button inside the context input (when creating a new conversation) and the same button inside the prompt input of the conversation. When either of these buttons is pressed, a popup or dropdown shows the saved prompts (maybe with a name instead of the entire prompt? or maybe with an ellipsis "..."?). I'm open to different display methods, I've never had the same use case as you so you might have better insight into it!

I'd be happy to work on it soon, or I can leave it to you if you'd like.

**Comment by maxijonson** [comment]
@guilhermelimak did you plan on implementing this? Just so I know before I work on something you're already working on 😅

**Comment by guilhermelimak** [comment]
hey, sorry about the silence. I will not be able to work on this for at least a couple of days, I'll post here to let you know if I start working on this so we don't do the same work twice

**Comment by maxijonson** [comment]
I'll start working on it and hopefully get it out pretty soon! 😁

**Comment by maxijonson** [comment]
Hey, just a heads up that the feature has been implemented. However, upon deployment, I've noticed the app totally crashes because of an invalid persistence state in local storage. Because this will affect most returning users, I've rolled back to the previous deployment until a fix is out for this bug. Will let you know when it's deployed!

**Comment by maxijonson** [comment]
Fixed by #18. It's now live on the web app!

**Comment by guilhermelimak** [comment]
This works wonderfully! Thansk a lot for taking the time to add this feature. Your app is great, I've been using it daily.
