### ISSUE TITLE
[Enchancement]: Add a save command to the CLI

### ISSUE THREAD

**Issue by jjbell150** [maxijonson/gpt-turbo#3]
### Type

New feature

### Description

It would be great to have a command that would save the current chat history to a timestamped file. As an extension of this, it would be very useful to have a flag that would do this automatically by creating a file on launch, and then append requests and responses to it.

### Benefit

One of the main drawbacks of gpt-turbo-cli is that I can't save my chat history, which is a critical feature. It's much nicer to use than other CLIs, so it would be great if this was possible in any form.

### Participation

No

**Comment by maxijonson** [comment]
Hi, I just wanted to give you a follow-up! 

That's a great idea I've wanted to explore but I left it on the side due to some questions I've been asking myself on what kind of data to save, where to save it, and how to load it. Your idea of a timestamped file is a good idea. One could specify a flag (--save or GPTTURBO_SAVE environment variable) to indicate they'd like to save the conversation, optionally specifying a file name. Loading could also be done with a flag (--load or GPTTURBO_LOAD). 

I'm currently working on the Web implementation of GPT Turbo (under the `impl/web` branch, at the time of writing), which is leading to major API changes (e.g. ditching OpenAI's Node SDK and using fetch instead, for compatibility). There's also a save functionality, which is good for laying a foundation for how I will approach this new feature for the CLI. So I'll work on this issue as soon as I'm ready to merge the Web implementation!

**Comment by maxijonson** [comment]
Sorry, just reopening temporarily until `3.1.0` can be published with this feature. I'm getting an error from NPM "Too many requests", which is quite odd considering I've published over 5 times in a single day in this library's beginnings 😅 Will try tomorrow!

**Comment by maxijonson** [comment]
It was successfully published this afternoon! you should have it by installing the latest version (3.1.0) `npm i -g gpt-turbo-cli`. Let me know what you think! Thanks!

**Comment by jjbell150** [comment]
Thanks for adding this! It works great, so much easier than trying to copy/paste the output from a terminal
